### ISSUE TITLE
Can we modify this code so that we can record calls on Android 10+ ?

### ISSUE THREAD

**Issue by javlonrahimov** [bourbonkk/NativeRecorder#2]

**Comment by bourbonkk** [comment]
From Android 10+, fake dl_open is blocked by Google policy. I tried a lot, but I couldn't make it. Sorry

**Comment by javlonrahimov** [comment]
> From Android 10+, fake dl_open is blocked by Google policy. I tried a lot, but I couldn't make it. Sorry

I see, thanks for your reply.
